apiVersion: v1
kind: Secret
metadata:
  name: my-db-secret
type: Opaque
data:
  DB_Host: bXlzcWw=   # base64 encoded value of 'mysql'
  DB_User: cm9vdA==   # base64 encoded value of 'root'
  DB_Password: cGFzd3Jk   # base64 encoded value of 'paswrd'