apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: myapp
    image: nginx
    env:
    - name: DATABASE_HOST
      valueFrom:
        secretKeyRef:
          name: my-db-secret
          key: DB_Host
    - name: DATABASE_USER
      valueFrom:
        secretKeyRef:
          name: my-db-secret
          key: DB_User
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-db-secret
          key: DB_Password