apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: secure-ns
  labels:
    app: database
    environment: production
type: Opaque
data:
  username: YWRtaW4= # base64 encoded value of 'admin'
  password: c2VjcmV0cGFzc3dvcmQ= # base64 encoded value of 'secretpassword'
  host: bXlzcWwuZGVmYXVsdC5zdmM= # base64 encoded value of 'mysql.default.svc'
  port: MzMwNg== # base64 encoded value of '3306'
  database: YXBwX2Ri # base64 encoded value of 'app_db'
